In [74]:
#Lets load required libraries

In [75]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [76]:
df = pd.read_csv("Clean Data.csv")

# Using Train Test Split on df

In [77]:
X = df.drop('LoanStatus Yes', axis=1)

In [78]:
y = df['LoanStatus Yes']

In [79]:
from sklearn.model_selection import train_test_split

In [80]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 101)

# Building a Logistic Regression Model

In [81]:
from sklearn.linear_model import LogisticRegression

In [82]:
logmodel = LogisticRegression()

In [83]:
logmodel.fit(X_train, y_train)

LogisticRegression()

In [84]:
predictions_log = logmodel.predict(X_test)

In [85]:
from sklearn.metrics import classification_report

In [86]:
print(classification_report(y_test, predictions_log))

              precision    recall  f1-score   support

           0       0.87      0.41      0.55        64
           1       0.75      0.97      0.85       121

    accuracy                           0.77       185
   macro avg       0.81      0.69      0.70       185
weighted avg       0.79      0.77      0.75       185



In [87]:
#Confusion Matrix

In [88]:
from sklearn.metrics import confusion_matrix

In [89]:
confusion_matrix(y_test, predictions_log)

array([[ 26,  38],
       [  4, 117]], dtype=int64)

# Building a Naive Bayes Classifier

In [90]:
from sklearn.naive_bayes import GaussianNB

In [91]:
model_nb = GaussianNB()

In [92]:
model_nb.fit(X_train, y_train)

GaussianNB()

In [93]:
predictions_nb = model_nb.predict(X_test)

In [94]:
print(classification_report(y_test, predictions_nb))

              precision    recall  f1-score   support

           0       0.93      0.41      0.57        64
           1       0.76      0.98      0.86       121

    accuracy                           0.78       185
   macro avg       0.84      0.69      0.71       185
weighted avg       0.82      0.78      0.76       185



In [95]:
confusion_matrix(y_test, predictions_nb)

array([[ 26,  38],
       [  2, 119]], dtype=int64)

# Building a Decision Tree Model

In [96]:
from sklearn.tree import DecisionTreeClassifier

In [97]:
dtree = DecisionTreeClassifier()

In [98]:
dtree.fit(X_train, y_train)

DecisionTreeClassifier()

In [99]:
predictions_dtree = dtree.predict(X_test)

In [100]:
print(classification_report(y_test, predictions_dtree))

              precision    recall  f1-score   support

           0       0.55      0.56      0.55        64
           1       0.76      0.75      0.76       121

    accuracy                           0.69       185
   macro avg       0.66      0.66      0.66       185
weighted avg       0.69      0.69      0.69       185



In [101]:
print(confusion_matrix(y_test, predictions_dtree))

[[36 28]
 [30 91]]


# Building a Random Forest Classifier

In [102]:
from sklearn.ensemble import RandomForestClassifier

In [103]:
rfc = RandomForestClassifier(n_estimators=300)

In [104]:
rfc.fit(X_train, y_train)

RandomForestClassifier(n_estimators=300)

In [105]:
rfc_pred = rfc.predict(X_test)

In [106]:
print(classification_report(y_test, rfc_pred))

              precision    recall  f1-score   support

           0       0.81      0.45      0.58        64
           1       0.77      0.94      0.84       121

    accuracy                           0.77       185
   macro avg       0.79      0.70      0.71       185
weighted avg       0.78      0.77      0.75       185



In [107]:
print(confusion_matrix(y_test,rfc_pred))

[[ 29  35]
 [  7 114]]
